name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Dependency
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.4
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
